url bugs fixed
Sudhee-bsp/Clipnow pull request #11
Opened 2023-03-04 19:09 UTC by ChsPranav

@Sudhee-bsp  ClipID url will only accept Alphanumeric

2023-03-06 16:31 UTC, Sudhee-bsp commented on src/components/board.jsx
> +      <p>Note: Only Alphanumerics are allowed</p>
@ChsPranav, Please remove the 'p' tag statement, as the ID validation message will be shown by the browser itself.

2023-03-06 16:32 UTC, Sudhee-bsp requested changes
Please fix with requested changes. @ChsPranav

2023-03-08 13:31 UTC, ChsPranav commented
@Sudhee-bsp  changes are done as per your request. please check it out.

2023-03-08 13:51 UTC, Sudhee-bsp commented
Reopening #11

2023-03-08 13:53 UTC, Sudhee-bsp approved these changes
Done.

2023-03-08 13:54 UTC, merged